// Code generated by vm/runtime/helpers/main.go. DO NOT EDIT.

package runtime

import (
	"fmt"
	"reflect"
	"time"

	"github.com/shopspring/decimal"
)

func Equal(a, b interface{}) bool {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Equal(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Equal(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Equal(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Equal(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).Equal(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).Equal(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Equal(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Equal(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).Equal(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) == int(y)
		case uint8:
			return int(x) == int(y)
		case uint16:
			return int(x) == int(y)
		case uint32:
			return int(x) == int(y)
		case uint64:
			return int(x) == int(y)
		case int:
			return int(x) == int(y)
		case int8:
			return int(x) == int(y)
		case int16:
			return int(x) == int(y)
		case int32:
			return int(x) == int(y)
		case int64:
			return int(x) == int(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).Equal(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) == float64(y)
		case uint8:
			return float64(x) == float64(y)
		case uint16:
			return float64(x) == float64(y)
		case uint32:
			return float64(x) == float64(y)
		case uint64:
			return float64(x) == float64(y)
		case int:
			return float64(x) == float64(y)
		case int8:
			return float64(x) == float64(y)
		case int16:
			return float64(x) == float64(y)
		case int32:
			return float64(x) == float64(y)
		case int64:
			return float64(x) == float64(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).Equal(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) == float64(y)
		case uint8:
			return float64(x) == float64(y)
		case uint16:
			return float64(x) == float64(y)
		case uint32:
			return float64(x) == float64(y)
		case uint64:
			return float64(x) == float64(y)
		case int:
			return float64(x) == float64(y)
		case int8:
			return float64(x) == float64(y)
		case int16:
			return float64(x) == float64(y)
		case int32:
			return float64(x) == float64(y)
		case int64:
			return float64(x) == float64(y)
		case float32:
			return float64(x) == float64(y)
		case float64:
			return float64(x) == float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).Equal(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.Equal(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.Equal(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.Equal(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.Equal(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.Equal(decimal.NewFromUint64(y))
		case int:
			return x.Equal(decimal.NewFromInt(int64(y)))
		case int8:
			return x.Equal(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.Equal(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.Equal(decimal.NewFromInt32(y))
		case int64:
			return x.Equal(decimal.NewFromInt(y))
		case float32:
			return x.Equal(decimal.NewFromFloat32(y))
		case float64:
			return x.Equal(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.Equal(y)
		}
	case []any:
		switch y := b.(type) {
		case []string:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []uint:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []uint8:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []uint16:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []uint32:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []uint64:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []int:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []int8:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []int16:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []int32:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []int64:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []float32:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []float64:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []decimal.Decimal:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		case []any:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if !Equal(x[i], y[i]) {
					return false
				}
			}
			return true
		}
	case []string:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []string:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []uint:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []uint:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []uint8:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []uint8:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []uint16:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []uint16:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []uint32:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []uint32:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []uint64:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []uint64:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []int:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []int:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []int8:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []int8:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []int16:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []int16:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []int32:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []int32:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []int64:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []int64:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []float32:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []float32:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []float64:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []float64:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case []decimal.Decimal:
		switch y := b.(type) {
		case []any:
			return Equal(y, x)
		case []decimal.Decimal:
			if len(x) != len(y) {
				return false
			}
			for i := range x {
				if x[i] != y[i] {
					return false
				}
			}
			return true
		}
	case string:
		switch y := b.(type) {
		case string:
			return x == y
		}
	case time.Time:
		switch y := b.(type) {
		case time.Time:
			return x.Equal(y)
		}
	case time.Duration:
		switch y := b.(type) {
		case time.Duration:
			return x == y
		}
	case bool:
		switch y := b.(type) {
		case bool:
			return x == y
		}
	}
	if IsNil(a) && IsNil(b) {
		return true
	}
	return reflect.DeepEqual(a, b)
}

func Less(a, b interface{}) bool {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThan(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThan(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThan(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThan(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).LessThan(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).LessThan(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).LessThan(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).LessThan(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).LessThan(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) < int(y)
		case uint8:
			return int(x) < int(y)
		case uint16:
			return int(x) < int(y)
		case uint32:
			return int(x) < int(y)
		case uint64:
			return int(x) < int(y)
		case int:
			return int(x) < int(y)
		case int8:
			return int(x) < int(y)
		case int16:
			return int(x) < int(y)
		case int32:
			return int(x) < int(y)
		case int64:
			return int(x) < int(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).LessThan(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) < float64(y)
		case uint8:
			return float64(x) < float64(y)
		case uint16:
			return float64(x) < float64(y)
		case uint32:
			return float64(x) < float64(y)
		case uint64:
			return float64(x) < float64(y)
		case int:
			return float64(x) < float64(y)
		case int8:
			return float64(x) < float64(y)
		case int16:
			return float64(x) < float64(y)
		case int32:
			return float64(x) < float64(y)
		case int64:
			return float64(x) < float64(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).LessThan(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) < float64(y)
		case uint8:
			return float64(x) < float64(y)
		case uint16:
			return float64(x) < float64(y)
		case uint32:
			return float64(x) < float64(y)
		case uint64:
			return float64(x) < float64(y)
		case int:
			return float64(x) < float64(y)
		case int8:
			return float64(x) < float64(y)
		case int16:
			return float64(x) < float64(y)
		case int32:
			return float64(x) < float64(y)
		case int64:
			return float64(x) < float64(y)
		case float32:
			return float64(x) < float64(y)
		case float64:
			return float64(x) < float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).LessThan(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.LessThan(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.LessThan(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.LessThan(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.LessThan(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.LessThan(decimal.NewFromUint64(y))
		case int:
			return x.LessThan(decimal.NewFromInt(int64(y)))
		case int8:
			return x.LessThan(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.LessThan(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.LessThan(decimal.NewFromInt32(y))
		case int64:
			return x.LessThan(decimal.NewFromInt(y))
		case float32:
			return x.LessThan(decimal.NewFromFloat32(y))
		case float64:
			return x.LessThan(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.LessThan(y)
		}
	case string:
		switch y := b.(type) {
		case string:
			return x < y
		}
	case time.Time:
		switch y := b.(type) {
		case time.Time:
			return x.Before(y)
		}
	case time.Duration:
		switch y := b.(type) {
		case time.Duration:
			return x < y
		}
	}
	panic(fmt.Sprintf("invalid operation: %T < %T", a, b))
}

func More(a, b interface{}) bool {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThan(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThan(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThan(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThan(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).GreaterThan(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).GreaterThan(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).GreaterThan(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).GreaterThan(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).GreaterThan(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) > int(y)
		case uint8:
			return int(x) > int(y)
		case uint16:
			return int(x) > int(y)
		case uint32:
			return int(x) > int(y)
		case uint64:
			return int(x) > int(y)
		case int:
			return int(x) > int(y)
		case int8:
			return int(x) > int(y)
		case int16:
			return int(x) > int(y)
		case int32:
			return int(x) > int(y)
		case int64:
			return int(x) > int(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).GreaterThan(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) > float64(y)
		case uint8:
			return float64(x) > float64(y)
		case uint16:
			return float64(x) > float64(y)
		case uint32:
			return float64(x) > float64(y)
		case uint64:
			return float64(x) > float64(y)
		case int:
			return float64(x) > float64(y)
		case int8:
			return float64(x) > float64(y)
		case int16:
			return float64(x) > float64(y)
		case int32:
			return float64(x) > float64(y)
		case int64:
			return float64(x) > float64(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).GreaterThan(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) > float64(y)
		case uint8:
			return float64(x) > float64(y)
		case uint16:
			return float64(x) > float64(y)
		case uint32:
			return float64(x) > float64(y)
		case uint64:
			return float64(x) > float64(y)
		case int:
			return float64(x) > float64(y)
		case int8:
			return float64(x) > float64(y)
		case int16:
			return float64(x) > float64(y)
		case int32:
			return float64(x) > float64(y)
		case int64:
			return float64(x) > float64(y)
		case float32:
			return float64(x) > float64(y)
		case float64:
			return float64(x) > float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).GreaterThan(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.GreaterThan(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.GreaterThan(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.GreaterThan(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.GreaterThan(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.GreaterThan(decimal.NewFromUint64(y))
		case int:
			return x.GreaterThan(decimal.NewFromInt(int64(y)))
		case int8:
			return x.GreaterThan(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.GreaterThan(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.GreaterThan(decimal.NewFromInt32(y))
		case int64:
			return x.GreaterThan(decimal.NewFromInt(y))
		case float32:
			return x.GreaterThan(decimal.NewFromFloat32(y))
		case float64:
			return x.GreaterThan(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.GreaterThan(y)
		}
	case string:
		switch y := b.(type) {
		case string:
			return x > y
		}
	case time.Time:
		switch y := b.(type) {
		case time.Time:
			return x.After(y)
		}
	case time.Duration:
		switch y := b.(type) {
		case time.Duration:
			return x > y
		}
	}
	panic(fmt.Sprintf("invalid operation: %T > %T", a, b))
}

func LessOrEqual(a, b interface{}) bool {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThanOrEqual(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThanOrEqual(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThanOrEqual(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).LessThanOrEqual(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).LessThanOrEqual(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).LessThanOrEqual(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).LessThanOrEqual(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).LessThanOrEqual(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).LessThanOrEqual(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) <= int(y)
		case uint8:
			return int(x) <= int(y)
		case uint16:
			return int(x) <= int(y)
		case uint32:
			return int(x) <= int(y)
		case uint64:
			return int(x) <= int(y)
		case int:
			return int(x) <= int(y)
		case int8:
			return int(x) <= int(y)
		case int16:
			return int(x) <= int(y)
		case int32:
			return int(x) <= int(y)
		case int64:
			return int(x) <= int(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).LessThanOrEqual(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) <= float64(y)
		case uint8:
			return float64(x) <= float64(y)
		case uint16:
			return float64(x) <= float64(y)
		case uint32:
			return float64(x) <= float64(y)
		case uint64:
			return float64(x) <= float64(y)
		case int:
			return float64(x) <= float64(y)
		case int8:
			return float64(x) <= float64(y)
		case int16:
			return float64(x) <= float64(y)
		case int32:
			return float64(x) <= float64(y)
		case int64:
			return float64(x) <= float64(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).LessThanOrEqual(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) <= float64(y)
		case uint8:
			return float64(x) <= float64(y)
		case uint16:
			return float64(x) <= float64(y)
		case uint32:
			return float64(x) <= float64(y)
		case uint64:
			return float64(x) <= float64(y)
		case int:
			return float64(x) <= float64(y)
		case int8:
			return float64(x) <= float64(y)
		case int16:
			return float64(x) <= float64(y)
		case int32:
			return float64(x) <= float64(y)
		case int64:
			return float64(x) <= float64(y)
		case float32:
			return float64(x) <= float64(y)
		case float64:
			return float64(x) <= float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).LessThanOrEqual(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.LessThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.LessThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.LessThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.LessThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.LessThanOrEqual(decimal.NewFromUint64(y))
		case int:
			return x.LessThanOrEqual(decimal.NewFromInt(int64(y)))
		case int8:
			return x.LessThanOrEqual(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.LessThanOrEqual(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.LessThanOrEqual(decimal.NewFromInt32(y))
		case int64:
			return x.LessThanOrEqual(decimal.NewFromInt(y))
		case float32:
			return x.LessThanOrEqual(decimal.NewFromFloat32(y))
		case float64:
			return x.LessThanOrEqual(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.LessThanOrEqual(y)
		}
	case string:
		switch y := b.(type) {
		case string:
			return x <= y
		}
	case time.Time:
		switch y := b.(type) {
		case time.Time:
			return x.Before(y) || x.Equal(y)
		}
	case time.Duration:
		switch y := b.(type) {
		case time.Duration:
			return x <= y
		}
	}
	panic(fmt.Sprintf("invalid operation: %T <= %T", a, b))
}

func MoreOrEqual(a, b interface{}) bool {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThanOrEqual(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThanOrEqual(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThanOrEqual(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).GreaterThanOrEqual(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).GreaterThanOrEqual(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).GreaterThanOrEqual(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).GreaterThanOrEqual(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).GreaterThanOrEqual(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).GreaterThanOrEqual(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) >= int(y)
		case uint8:
			return int(x) >= int(y)
		case uint16:
			return int(x) >= int(y)
		case uint32:
			return int(x) >= int(y)
		case uint64:
			return int(x) >= int(y)
		case int:
			return int(x) >= int(y)
		case int8:
			return int(x) >= int(y)
		case int16:
			return int(x) >= int(y)
		case int32:
			return int(x) >= int(y)
		case int64:
			return int(x) >= int(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).GreaterThanOrEqual(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) >= float64(y)
		case uint8:
			return float64(x) >= float64(y)
		case uint16:
			return float64(x) >= float64(y)
		case uint32:
			return float64(x) >= float64(y)
		case uint64:
			return float64(x) >= float64(y)
		case int:
			return float64(x) >= float64(y)
		case int8:
			return float64(x) >= float64(y)
		case int16:
			return float64(x) >= float64(y)
		case int32:
			return float64(x) >= float64(y)
		case int64:
			return float64(x) >= float64(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).GreaterThanOrEqual(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) >= float64(y)
		case uint8:
			return float64(x) >= float64(y)
		case uint16:
			return float64(x) >= float64(y)
		case uint32:
			return float64(x) >= float64(y)
		case uint64:
			return float64(x) >= float64(y)
		case int:
			return float64(x) >= float64(y)
		case int8:
			return float64(x) >= float64(y)
		case int16:
			return float64(x) >= float64(y)
		case int32:
			return float64(x) >= float64(y)
		case int64:
			return float64(x) >= float64(y)
		case float32:
			return float64(x) >= float64(y)
		case float64:
			return float64(x) >= float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).GreaterThanOrEqual(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.GreaterThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.GreaterThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.GreaterThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.GreaterThanOrEqual(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.GreaterThanOrEqual(decimal.NewFromUint64(y))
		case int:
			return x.GreaterThanOrEqual(decimal.NewFromInt(int64(y)))
		case int8:
			return x.GreaterThanOrEqual(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.GreaterThanOrEqual(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.GreaterThanOrEqual(decimal.NewFromInt32(y))
		case int64:
			return x.GreaterThanOrEqual(decimal.NewFromInt(y))
		case float32:
			return x.GreaterThanOrEqual(decimal.NewFromFloat32(y))
		case float64:
			return x.GreaterThanOrEqual(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.GreaterThanOrEqual(y)
		}
	case string:
		switch y := b.(type) {
		case string:
			return x >= y
		}
	case time.Time:
		switch y := b.(type) {
		case time.Time:
			return x.After(y) || x.Equal(y)
		}
	case time.Duration:
		switch y := b.(type) {
		case time.Duration:
			return x >= y
		}
	}
	panic(fmt.Sprintf("invalid operation: %T >= %T", a, b))
}

func Add(a, b interface{}) interface{} {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Add(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Add(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Add(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Add(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).Add(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).Add(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Add(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Add(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).Add(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) + int(y)
		case uint8:
			return int(x) + int(y)
		case uint16:
			return int(x) + int(y)
		case uint32:
			return int(x) + int(y)
		case uint64:
			return int(x) + int(y)
		case int:
			return int(x) + int(y)
		case int8:
			return int(x) + int(y)
		case int16:
			return int(x) + int(y)
		case int32:
			return int(x) + int(y)
		case int64:
			return int(x) + int(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).Add(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) + float64(y)
		case uint8:
			return float64(x) + float64(y)
		case uint16:
			return float64(x) + float64(y)
		case uint32:
			return float64(x) + float64(y)
		case uint64:
			return float64(x) + float64(y)
		case int:
			return float64(x) + float64(y)
		case int8:
			return float64(x) + float64(y)
		case int16:
			return float64(x) + float64(y)
		case int32:
			return float64(x) + float64(y)
		case int64:
			return float64(x) + float64(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).Add(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) + float64(y)
		case uint8:
			return float64(x) + float64(y)
		case uint16:
			return float64(x) + float64(y)
		case uint32:
			return float64(x) + float64(y)
		case uint64:
			return float64(x) + float64(y)
		case int:
			return float64(x) + float64(y)
		case int8:
			return float64(x) + float64(y)
		case int16:
			return float64(x) + float64(y)
		case int32:
			return float64(x) + float64(y)
		case int64:
			return float64(x) + float64(y)
		case float32:
			return float64(x) + float64(y)
		case float64:
			return float64(x) + float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).Add(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.Add(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.Add(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.Add(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.Add(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.Add(decimal.NewFromUint64(y))
		case int:
			return x.Add(decimal.NewFromInt(int64(y)))
		case int8:
			return x.Add(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.Add(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.Add(decimal.NewFromInt32(y))
		case int64:
			return x.Add(decimal.NewFromInt(y))
		case float32:
			return x.Add(decimal.NewFromFloat32(y))
		case float64:
			return x.Add(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.Add(y)
		}
	case string:
		switch y := b.(type) {
		case string:
			return x + y
		}
	case time.Time:
		switch y := b.(type) {
		case time.Duration:
			return x.Add(y)
		}
	case time.Duration:
		switch y := b.(type) {
		case time.Time:
			return y.Add(x)
		case time.Duration:
			return x + y
		}
	}
	panic(fmt.Sprintf("invalid operation: %T + %T", a, b))
}

func Subtract(a, b interface{}) interface{} {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Sub(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Sub(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Sub(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Sub(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).Sub(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).Sub(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Sub(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Sub(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).Sub(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) - int(y)
		case uint8:
			return int(x) - int(y)
		case uint16:
			return int(x) - int(y)
		case uint32:
			return int(x) - int(y)
		case uint64:
			return int(x) - int(y)
		case int:
			return int(x) - int(y)
		case int8:
			return int(x) - int(y)
		case int16:
			return int(x) - int(y)
		case int32:
			return int(x) - int(y)
		case int64:
			return int(x) - int(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).Sub(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) - float64(y)
		case uint8:
			return float64(x) - float64(y)
		case uint16:
			return float64(x) - float64(y)
		case uint32:
			return float64(x) - float64(y)
		case uint64:
			return float64(x) - float64(y)
		case int:
			return float64(x) - float64(y)
		case int8:
			return float64(x) - float64(y)
		case int16:
			return float64(x) - float64(y)
		case int32:
			return float64(x) - float64(y)
		case int64:
			return float64(x) - float64(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).Sub(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) - float64(y)
		case uint8:
			return float64(x) - float64(y)
		case uint16:
			return float64(x) - float64(y)
		case uint32:
			return float64(x) - float64(y)
		case uint64:
			return float64(x) - float64(y)
		case int:
			return float64(x) - float64(y)
		case int8:
			return float64(x) - float64(y)
		case int16:
			return float64(x) - float64(y)
		case int32:
			return float64(x) - float64(y)
		case int64:
			return float64(x) - float64(y)
		case float32:
			return float64(x) - float64(y)
		case float64:
			return float64(x) - float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).Sub(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.Sub(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.Sub(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.Sub(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.Sub(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.Sub(decimal.NewFromUint64(y))
		case int:
			return x.Sub(decimal.NewFromInt(int64(y)))
		case int8:
			return x.Sub(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.Sub(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.Sub(decimal.NewFromInt32(y))
		case int64:
			return x.Sub(decimal.NewFromInt(y))
		case float32:
			return x.Sub(decimal.NewFromFloat32(y))
		case float64:
			return x.Sub(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.Sub(y)
		}
	case time.Time:
		switch y := b.(type) {
		case time.Time:
			return x.Sub(y)
		case time.Duration:
			return x.Add(-y)
		}
	case time.Duration:
		switch y := b.(type) {
		case time.Duration:
			return x - y
		}
	}
	panic(fmt.Sprintf("invalid operation: %T - %T", a, b))
}

func Multiply(a, b interface{}) interface{} {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) * int(y)
		case uint8:
			return int(x) * int(y)
		case uint16:
			return int(x) * int(y)
		case uint32:
			return int(x) * int(y)
		case uint64:
			return int(x) * int(y)
		case int:
			return int(x) * int(y)
		case int8:
			return int(x) * int(y)
		case int16:
			return int(x) * int(y)
		case int32:
			return int(x) * int(y)
		case int64:
			return int(x) * int(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) * float64(y)
		case uint8:
			return float64(x) * float64(y)
		case uint16:
			return float64(x) * float64(y)
		case uint32:
			return float64(x) * float64(y)
		case uint64:
			return float64(x) * float64(y)
		case int:
			return float64(x) * float64(y)
		case int8:
			return float64(x) * float64(y)
		case int16:
			return float64(x) * float64(y)
		case int32:
			return float64(x) * float64(y)
		case int64:
			return float64(x) * float64(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).Mul(y)
		case time.Duration:
			return float64(x) * float64(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) * float64(y)
		case uint8:
			return float64(x) * float64(y)
		case uint16:
			return float64(x) * float64(y)
		case uint32:
			return float64(x) * float64(y)
		case uint64:
			return float64(x) * float64(y)
		case int:
			return float64(x) * float64(y)
		case int8:
			return float64(x) * float64(y)
		case int16:
			return float64(x) * float64(y)
		case int32:
			return float64(x) * float64(y)
		case int64:
			return float64(x) * float64(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).Mul(y)
		case time.Duration:
			return float64(x) * float64(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.Mul(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.Mul(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.Mul(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.Mul(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.Mul(decimal.NewFromUint64(y))
		case int:
			return x.Mul(decimal.NewFromInt(int64(y)))
		case int8:
			return x.Mul(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.Mul(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.Mul(decimal.NewFromInt32(y))
		case int64:
			return x.Mul(decimal.NewFromInt(y))
		case float32:
			return x.Mul(decimal.NewFromFloat32(y))
		case float64:
			return x.Mul(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.Mul(y)
		case time.Duration:
			return x.Mul(decimal.NewFromInt(int64(y)))
		}
	case time.Duration:
		switch y := b.(type) {
		case uint:
			return time.Duration(x) * time.Duration(y)
		case uint8:
			return time.Duration(x) * time.Duration(y)
		case uint16:
			return time.Duration(x) * time.Duration(y)
		case uint32:
			return time.Duration(x) * time.Duration(y)
		case uint64:
			return time.Duration(x) * time.Duration(y)
		case int:
			return time.Duration(x) * time.Duration(y)
		case int8:
			return time.Duration(x) * time.Duration(y)
		case int16:
			return time.Duration(x) * time.Duration(y)
		case int32:
			return time.Duration(x) * time.Duration(y)
		case int64:
			return time.Duration(x) * time.Duration(y)
		case float32:
			return float64(x) * float64(y)
		case float64:
			return float64(x) * float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).Mul(y)
		case time.Duration:
			return time.Duration(x) * time.Duration(y)
		}
	}
	panic(fmt.Sprintf("invalid operation: %T * %T", a, b))
}

func Divide(a, b interface{}) interface{} {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Div(y)
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Div(y)
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Div(y)
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(uint64(x)).Div(y)
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromUint64(x).Div(y)
		}
	case int:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(int64(x)).Div(y)
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Div(y)
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(int32(x)).Div(y)
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt32(x).Div(y)
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromInt(x).Div(y)
		}
	case float32:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat32(x).Div(y)
		}
	case float64:
		switch y := b.(type) {
		case uint:
			return float64(x) / float64(y)
		case uint8:
			return float64(x) / float64(y)
		case uint16:
			return float64(x) / float64(y)
		case uint32:
			return float64(x) / float64(y)
		case uint64:
			return float64(x) / float64(y)
		case int:
			return float64(x) / float64(y)
		case int8:
			return float64(x) / float64(y)
		case int16:
			return float64(x) / float64(y)
		case int32:
			return float64(x) / float64(y)
		case int64:
			return float64(x) / float64(y)
		case float32:
			return float64(x) / float64(y)
		case float64:
			return float64(x) / float64(y)
		case decimal.Decimal:
			return decimal.NewFromFloat(x).Div(y)
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return x.Div(decimal.NewFromUint64(uint64(y)))
		case uint8:
			return x.Div(decimal.NewFromUint64(uint64(y)))
		case uint16:
			return x.Div(decimal.NewFromUint64(uint64(y)))
		case uint32:
			return x.Div(decimal.NewFromUint64(uint64(y)))
		case uint64:
			return x.Div(decimal.NewFromUint64(y))
		case int:
			return x.Div(decimal.NewFromInt(int64(y)))
		case int8:
			return x.Div(decimal.NewFromInt32(int32(y)))
		case int16:
			return x.Div(decimal.NewFromInt32(int32(y)))
		case int32:
			return x.Div(decimal.NewFromInt32(y))
		case int64:
			return x.Div(decimal.NewFromInt(y))
		case float32:
			return x.Div(decimal.NewFromFloat32(y))
		case float64:
			return x.Div(decimal.NewFromFloat(y))
		case decimal.Decimal:
			return x.Div(y)
		}
	}
	panic(fmt.Sprintf("invalid operation: %T / %T", a, b))
}

func Modulo(a, b interface{}) int {
	switch x := a.(type) {
	case uint:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromUint64(uint64(x)).Mod(y).IntPart())
		}
	case uint8:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromUint64(uint64(x)).Mod(y).IntPart())
		}
	case uint16:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromUint64(uint64(x)).Mod(y).IntPart())
		}
	case uint32:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromUint64(uint64(x)).Mod(y).IntPart())
		}
	case uint64:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromUint64(x).Mod(y).IntPart())
		}
	case int:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromInt(int64(x)).Mod(y).IntPart())
		}
	case int8:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromInt32(int32(x)).Mod(y).IntPart())
		}
	case int16:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromInt32(int32(x)).Mod(y).IntPart())
		}
	case int32:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromInt32(x).Mod(y).IntPart())
		}
	case int64:
		switch y := b.(type) {
		case uint:
			return int(x) % int(y)
		case uint8:
			return int(x) % int(y)
		case uint16:
			return int(x) % int(y)
		case uint32:
			return int(x) % int(y)
		case uint64:
			return int(x) % int(y)
		case int:
			return int(x) % int(y)
		case int8:
			return int(x) % int(y)
		case int16:
			return int(x) % int(y)
		case int32:
			return int(x) % int(y)
		case int64:
			return int(x) % int(y)
		case decimal.Decimal:
			return int(decimal.NewFromInt(x).Mod(y).IntPart())
		}
	case decimal.Decimal:
		switch y := b.(type) {
		case uint:
			return int(x.Mod(decimal.NewFromUint64(uint64(y))).IntPart())
		case uint8:
			return int(x.Mod(decimal.NewFromUint64(uint64(y))).IntPart())
		case uint16:
			return int(x.Mod(decimal.NewFromUint64(uint64(y))).IntPart())
		case uint32:
			return int(x.Mod(decimal.NewFromUint64(uint64(y))).IntPart())
		case uint64:
			return int(x.Mod(decimal.NewFromUint64(y)).IntPart())
		case int:
			return int(x.Mod(decimal.NewFromInt(int64(y))).IntPart())
		case int8:
			return int(x.Mod(decimal.NewFromInt32(int32(y))).IntPart())
		case int16:
			return int(x.Mod(decimal.NewFromInt32(int32(y))).IntPart())
		case int32:
			return int(x.Mod(decimal.NewFromInt32(y)).IntPart())
		case int64:
			return int(x.Mod(decimal.NewFromInt(y)).IntPart())
		case decimal.Decimal:
			return int(x.Mod(y).IntPart())
		}
	}
	panic(fmt.Sprintf("invalid operation: %T %% %T", a, b))
}
